package gemini

import (
	"testing"
)

// TestGetFinishReasonMessage tests the GetFinishReasonMessage function
func TestGetFinishReasonMessage(t *testing.T) {
	tests := []struct {
		name         string
		finishReason string
		want         string
	}{
		{
			name:         "STOP reason",
			finishReason: string(FinishReasonStop),
			want:         "response completed successfully",
		},
		{
			name:         "MAX_TOKENS reason",
			finishReason: string(FinishReasonMaxTokens),
			want:         "maximum token limit reached",
		},
		{
			name:         "SAFETY reason",
			finishReason: string(FinishReasonSafety),
			want:         "content was flagged for safety concerns",
		},
		{
			name:         "RECITATION reason",
			finishReason: string(FinishReasonRecitation),
			want:         "content was flagged for potential recitation of copyrighted material",
		},
		{
			name:         "LANGUAGE reason",
			finishReason: string(FinishReasonLanguage),
			want:         "content was flagged for using an unsupported language",
		},
		{
			name:         "BLOCKLIST reason",
			finishReason: string(FinishReasonBlocklist),
			want:         "content contains forbidden terms from blocklist",
		},
		{
			name:         "PROHIBITED_CONTENT reason",
			finishReason: string(FinishReasonProhibitedContent),
			want:         "content was blocked for potentially containing prohibited content",
		},
		{
			name:         "SPII reason",
			finishReason: string(string(FinishReasonSpii)),
			want:         "content was blocked for potentially containing Sensitive Personally Identifiable Information (SPII)",
		},
		{
			name:         "MALFORMED_FUNCTION_CALL reason",
			finishReason: string(FinishReasonMalformedFunctionCall),
			want:         "function call generated by the model is invalid (consider using function calling mode ANY for constrained decoding)",
		},
		{
			name:         "IMAGE_SAFETY reason",
			finishReason: string(FinishReasonImageSafety),
			want:         "generated images contain safety violations",
		},
		{
			name:         "UNEXPECTED_TOOL_CALL reason",
			finishReason: string(FinishReasonUnexpectedToolCall),
			want:         "model generated a tool call but no tools were enabled in the request",
		},
		{
			name:         "TOO_MANY_TOOL_CALLS reason",
			finishReason: string(FinishReasonTooManyToolCalls),
			want:         "model called too many tools consecutively",
		},
		{
			name:         "IMAGE_PROHIBITED_CONTENT reason",
			finishReason: string(FinishReasonImageProhibitedContent),
			want:         "generated images contain prohibited content",
		},
		{
			name:         "IMAGE_OTHER reason",
			finishReason: string(FinishReasonImageOther),
			want:         "image generation stopped due to miscellaneous issue",
		},
		{
			name:         "NO_IMAGE reason",
			finishReason: string(FinishReasonNoImage),
			want:         "model was expected to generate an image but none was generated",
		},
		{
			name:         "OTHER reason",
			finishReason: string(FinishReasonOther),
			want:         "generation stopped for unknown reason",
		},
		{
			name:         "UNSPECIFIED reason",
			finishReason: string(FinishReasonUnspecified),
			want:         "finish reason unspecified",
		},
		{
			name:         "Empty reason",
			finishReason: "",
			want:         "finish reason unspecified",
		},
		{
			name:         "Unknown reason",
			finishReason: "UNKNOWN_REASON",
			want:         "generation stopped with reason: UNKNOWN_REASON",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := GetFinishReasonMessage(tt.finishReason)
			if got != tt.want {
				t.Errorf("GetFinishReasonMessage(%q) = %q, want %q", tt.finishReason, got, tt.want)
			}
		})
	}
}

// TestIsErrorFinishReason tests the IsErrorFinishReason function
func TestIsErrorFinishReason(t *testing.T) {
	tests := []struct {
		name         string
		finishReason string
		wantError    bool
	}{
		// Error reasons
		{
			name:         "SAFETY is error",
			finishReason: string(FinishReasonSafety),
			wantError:    true,
		},
		{
			name:         "RECITATION is error",
			finishReason: string(FinishReasonRecitation),
			wantError:    true,
		},
		{
			name:         "LANGUAGE is error",
			finishReason: string(FinishReasonLanguage),
			wantError:    true,
		},
		{
			name:         "BLOCKLIST is error",
			finishReason: string(FinishReasonBlocklist),
			wantError:    true,
		},
		{
			name:         "PROHIBITED_CONTENT is error",
			finishReason: string(FinishReasonProhibitedContent),
			wantError:    true,
		},
		{
			name:         "SPII is error",
			finishReason: string(FinishReasonSpii),
			wantError:    true,
		},
		{
			name:         "MALFORMED_FUNCTION_CALL is error",
			finishReason: string(FinishReasonMalformedFunctionCall),
			wantError:    true,
		},
		{
			name:         "IMAGE_SAFETY is error",
			finishReason: string(FinishReasonImageSafety),
			wantError:    true,
		},
		{
			name:         "UNEXPECTED_TOOL_CALL is error",
			finishReason: string(FinishReasonUnexpectedToolCall),
			wantError:    true,
		},
		{
			name:         "TOO_MANY_TOOL_CALLS is error",
			finishReason: string(FinishReasonTooManyToolCalls),
			wantError:    true,
		},
		{
			name:         "IMAGE_PROHIBITED_CONTENT is error",
			finishReason: string(FinishReasonImageProhibitedContent),
			wantError:    true,
		},
		{
			name:         "IMAGE_OTHER is error",
			finishReason: string(FinishReasonImageOther),
			wantError:    true,
		},
		{
			name:         "NO_IMAGE is error",
			finishReason: string(FinishReasonNoImage),
			wantError:    true,
		},
		// Non-error reasons
		{
			name:         "STOP is not error",
			finishReason: string(FinishReasonStop),
			wantError:    false,
		},
		{
			name:         "MAX_TOKENS is not error",
			finishReason: string(FinishReasonMaxTokens),
			wantError:    false,
		},
		{
			name:         "OTHER is not error",
			finishReason: string(FinishReasonOther),
			wantError:    false,
		},
		{
			name:         "UNSPECIFIED is not error",
			finishReason: string(FinishReasonUnspecified),
			wantError:    false,
		},
		{
			name:         "Empty is not error",
			finishReason: "",
			wantError:    false,
		},
		{
			name:         "Unknown is not error",
			finishReason: "UNKNOWN",
			wantError:    false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := IsErrorFinishReason(tt.finishReason)
			if got != tt.wantError {
				t.Errorf("IsErrorFinishReason(%q) = %v, want %v", tt.finishReason, got, tt.wantError)
			}
		})
	}
}

// TestMapGeminiFinishReasonToStandard tests the mapGeminiFinishReasonToStandard function
func TestMapGeminiFinishReasonToStandard(t *testing.T) {
	tests := []struct {
		name         string
		finishReason string
		hasToolCalls bool
		want         string
	}{
		// STOP mappings
		{
			name:         "STOP without tool calls",
			finishReason: string(FinishReasonStop),
			hasToolCalls: false,
			want:         "stop",
		},
		{
			name:         "STOP with tool calls",
			finishReason: string(FinishReasonStop),
			hasToolCalls: true,
			want:         "tool_calls",
		},
		// Length mapping
		{
			name:         "MAX_TOKENS maps to length",
			finishReason: string(FinishReasonMaxTokens),
			hasToolCalls: false,
			want:         "length",
		},
		// Content filter mappings
		{
			name:         "SAFETY maps to content_filter",
			finishReason: string(FinishReasonSafety),
			hasToolCalls: false,
			want:         "content_filter",
		},
		{
			name:         "RECITATION maps to content_filter",
			finishReason: string(FinishReasonRecitation),
			hasToolCalls: false,
			want:         "content_filter",
		},
		{
			name:         "LANGUAGE maps to content_filter",
			finishReason: string(FinishReasonLanguage),
			hasToolCalls: false,
			want:         "content_filter",
		},
		{
			name:         "BLOCKLIST maps to content_filter",
			finishReason: string(FinishReasonBlocklist),
			hasToolCalls: false,
			want:         "content_filter",
		},
		{
			name:         "PROHIBITED_CONTENT maps to content_filter",
			finishReason: string(FinishReasonProhibitedContent),
			hasToolCalls: false,
			want:         "content_filter",
		},
		{
			name:         "SPII maps to content_filter",
			finishReason: string(FinishReasonSpii),
			hasToolCalls: false,
			want:         "content_filter",
		},
		{
			name:         "IMAGE_SAFETY maps to content_filter",
			finishReason: string(FinishReasonImageSafety),
			hasToolCalls: false,
			want:         "content_filter",
		},
		{
			name:         "IMAGE_PROHIBITED_CONTENT maps to content_filter",
			finishReason: string(FinishReasonImageProhibitedContent),
			hasToolCalls: false,
			want:         "content_filter",
		},
		// Tool call error mappings
		{
			name:         "MALFORMED_FUNCTION_CALL maps to tool_calls",
			finishReason: string(FinishReasonMalformedFunctionCall),
			hasToolCalls: false,
			want:         "tool_calls",
		},
		{
			name:         "UNEXPECTED_TOOL_CALL maps to tool_calls",
			finishReason: string(FinishReasonUnexpectedToolCall),
			hasToolCalls: false,
			want:         "tool_calls",
		},
		{
			name:         "TOO_MANY_TOOL_CALLS maps to tool_calls",
			finishReason: string(FinishReasonTooManyToolCalls),
			hasToolCalls: false,
			want:         "tool_calls",
		},
		// Other mappings
		{
			name:         "NO_IMAGE maps to stop",
			finishReason: string(FinishReasonNoImage),
			hasToolCalls: false,
			want:         "stop",
		},
		{
			name:         "IMAGE_OTHER maps to stop",
			finishReason: string(FinishReasonImageOther),
			hasToolCalls: false,
			want:         "stop",
		},
		{
			name:         "OTHER maps to stop",
			finishReason: string(FinishReasonOther),
			hasToolCalls: false,
			want:         "stop",
		},
		{
			name:         "Unknown reason maps to stop",
			finishReason: "UNKNOWN",
			hasToolCalls: false,
			want:         "stop",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := mapGeminiFinishReasonToStandard(tt.finishReason, tt.hasToolCalls)
			if got != tt.want {
				t.Errorf("mapGeminiFinishReasonToStandard(%q, %v) = %q, want %q",
					tt.finishReason, tt.hasToolCalls, got, tt.want)
			}
		})
	}
}

// TestFinishReasonConstants verifies that all constants are defined correctly
func TestFinishReasonConstants(t *testing.T) {
	tests := []struct {
		name     string
		constant string
		expected string
	}{
		{"FinishReasonUnspecified", string(FinishReasonUnspecified), "FINISH_REASON_UNSPECIFIED"},
		{"FinishReasonStop", string(FinishReasonStop), "STOP"},
		{"FinishReasonMaxTokens", string(FinishReasonMaxTokens), "MAX_TOKENS"},
		{"FinishReasonSafety", string(FinishReasonSafety), "SAFETY"},
		{"FinishReasonRecitation", string(FinishReasonRecitation), "RECITATION"},
		{"FinishReasonLanguage", string(FinishReasonLanguage), "LANGUAGE"},
		{"FinishReasonOther", string(FinishReasonOther), "OTHER"},
		{"FinishReasonBlocklist", string(FinishReasonBlocklist), "BLOCKLIST"},
		{"FinishReasonProhibitedContent", string(FinishReasonProhibitedContent), "PROHIBITED_CONTENT"},
		{"FinishReasonSpii", string(FinishReasonSpii), "SPII"},
		{"FinishReasonMalformedFunctionCall", string(FinishReasonMalformedFunctionCall), "MALFORMED_FUNCTION_CALL"},
		{"FinishReasonImageSafety", string(FinishReasonImageSafety), "IMAGE_SAFETY"},
		{"FinishReasonUnexpectedToolCall", string(FinishReasonUnexpectedToolCall), "UNEXPECTED_TOOL_CALL"},
		{"FinishReasonTooManyToolCalls", string(FinishReasonTooManyToolCalls), "TOO_MANY_TOOL_CALLS"},
		{"FinishReasonImageProhibitedContent", string(FinishReasonImageProhibitedContent), "IMAGE_PROHIBITED_CONTENT"},
		{"FinishReasonImageOther", string(FinishReasonImageOther), "IMAGE_OTHER"},
		{"FinishReasonNoImage", string(FinishReasonNoImage), "NO_IMAGE"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if tt.constant != tt.expected {
				t.Errorf("%s = %q, want %q", tt.name, tt.constant, tt.expected)
			}
		})
	}
}
