package ollama

import (
	"encoding/json"
	"testing"

	"github.com/cecil-the-coder/ai-provider-kit/pkg/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestToolConversion_PolymorphicTypes tests that tools with polymorphic type fields
// are correctly converted and normalized for Ollama compatibility.
// This test addresses the issue reported in: https://github.com/ollama/ollama/issues/10328
func TestToolConversion_PolymorphicTypes(t *testing.T) {
	provider := &OllamaProvider{}

	// Define a tool with a JSON schema that includes polymorphic type fields
	// This is the format typically generated by tools like Vercel AI SDK
	tool := types.Tool{
		Name:        "get_weather",
		Description: "Get weather information for a location",
		InputSchema: map[string]interface{}{
			"type": "object",
			"properties": map[string]interface{}{
				"countryCode": map[string]interface{}{
					"type":        []interface{}{"string", "null"},
					"description": "The country code (ISO 3166-1 alpha-2)",
				},
				"city": map[string]interface{}{
					"type":        []interface{}{"string", "null"},
					"description": "The city name",
				},
				"temperature": map[string]interface{}{
					"type":        []interface{}{"number", "null"},
					"description": "The temperature in Celsius",
				},
			},
			"required": []string{"countryCode"},
		},
	}

	// Convert the tool to Ollama format
	ollamaTools := provider.convertTools([]types.Tool{tool})

	require.Len(t, ollamaTools, 1)
	ollamaTool := ollamaTools[0]

	// Verify basic structure
	assert.Equal(t, "function", ollamaTool.Type)
	assert.Equal(t, "get_weather", ollamaTool.Function.Name)
	assert.Equal(t, "Get weather information for a location", ollamaTool.Function.Description)

	// Verify that the schema was normalized (polymorphic types converted to strings)
	params := ollamaTool.Function.Parameters
	require.NotNil(t, params)

	properties, ok := params["properties"].(map[string]interface{})
	require.True(t, ok, "properties should be a map")

	// Check countryCode
	countryCode, ok := properties["countryCode"].(map[string]interface{})
	require.True(t, ok, "countryCode should be a map")
	assert.Equal(t, "string", countryCode["type"], "countryCode type should be normalized to string")
	assert.Equal(t, "The country code (ISO 3166-1 alpha-2)", countryCode["description"])

	// Check city
	city, ok := properties["city"].(map[string]interface{})
	require.True(t, ok, "city should be a map")
	assert.Equal(t, "string", city["type"], "city type should be normalized to string")

	// Check temperature
	temperature, ok := properties["temperature"].(map[string]interface{})
	require.True(t, ok, "temperature should be a map")
	assert.Equal(t, "number", temperature["type"], "temperature type should be normalized to number")

	// Verify the result can be marshaled to JSON without errors
	_, err := json.Marshal(ollamaTool)
	assert.NoError(t, err, "normalized tool should be marshallable to JSON")
}

// TestToolConversion_NestedPolymorphicTypes tests normalization of deeply nested schemas
func TestToolConversion_NestedPolymorphicTypes(t *testing.T) {
	provider := &OllamaProvider{}

	tool := types.Tool{
		Name:        "process_data",
		Description: "Process complex data structure",
		InputSchema: map[string]interface{}{
			"type": "object",
			"properties": map[string]interface{}{
				"user": map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"name": map[string]interface{}{
							"type": []interface{}{"string", "null"},
						},
						"age": map[string]interface{}{
							"type": []string{"number", "null"},
						},
						"tags": map[string]interface{}{
							"type": "array",
							"items": map[string]interface{}{
								"type": []interface{}{"string", "null"},
							},
						},
					},
				},
			},
		},
	}

	ollamaTools := provider.convertTools([]types.Tool{tool})
	require.Len(t, ollamaTools, 1)

	params := ollamaTools[0].Function.Parameters
	properties := params["properties"].(map[string]interface{})
	user := properties["user"].(map[string]interface{})
	userProps := user["properties"].(map[string]interface{})

	// Verify nested property types are normalized
	name := userProps["name"].(map[string]interface{})
	assert.Equal(t, "string", name["type"])

	age := userProps["age"].(map[string]interface{})
	assert.Equal(t, "number", age["type"])

	tags := userProps["tags"].(map[string]interface{})
	assert.Equal(t, "array", tags["type"])

	// Verify array items are also normalized
	items := tags["items"].(map[string]interface{})
	assert.Equal(t, "string", items["type"])
}

// TestToolConversion_PreservesSingleTypeFields tests that schemas with single-type
// fields are left unchanged
func TestToolConversion_PreservesSingleTypeFields(t *testing.T) {
	provider := &OllamaProvider{}

	tool := types.Tool{
		Name:        "simple_tool",
		Description: "A tool with simple types",
		InputSchema: map[string]interface{}{
			"type": "object",
			"properties": map[string]interface{}{
				"name": map[string]interface{}{
					"type":        "string",
					"description": "The name",
				},
				"count": map[string]interface{}{
					"type":        "integer",
					"description": "The count",
				},
			},
		},
	}

	ollamaTools := provider.convertTools([]types.Tool{tool})
	require.Len(t, ollamaTools, 1)

	params := ollamaTools[0].Function.Parameters
	properties := params["properties"].(map[string]interface{})

	name := properties["name"].(map[string]interface{})
	assert.Equal(t, "string", name["type"], "single string type should be preserved")

	count := properties["count"].(map[string]interface{})
	assert.Equal(t, "integer", count["type"], "single integer type should be preserved")
}

// TestToolConversion_HandlesNullFirstInArray tests that when null is the first
// type in an array, the first non-null type is used
func TestToolConversion_HandlesNullFirstInArray(t *testing.T) {
	provider := &OllamaProvider{}

	tool := types.Tool{
		Name:        "nullable_tool",
		Description: "A tool with null-first types",
		InputSchema: map[string]interface{}{
			"type": "object",
			"properties": map[string]interface{}{
				"value": map[string]interface{}{
					"type": []interface{}{"null", "string"},
				},
			},
		},
	}

	ollamaTools := provider.convertTools([]types.Tool{tool})
	require.Len(t, ollamaTools, 1)

	params := ollamaTools[0].Function.Parameters
	properties := params["properties"].(map[string]interface{})
	value := properties["value"].(map[string]interface{})

	// Should pick "string" since it's the first non-null type
	assert.Equal(t, "string", value["type"])
}

// TestToolConversion_RealWorldVercelAISDKExample tests with a real-world example
// from Vercel AI SDK that was causing the original issue
func TestToolConversion_RealWorldVercelAISDKExample(t *testing.T) {
	provider := &OllamaProvider{}

	// This is the exact schema format that Vercel AI SDK generates
	// which was causing the error: "cannot unmarshal array into Go struct field"
	tool := types.Tool{
		Name:        "getWeatherInformation",
		Description: "Get weather information for a given location",
		InputSchema: map[string]interface{}{
			"type": "object",
			"properties": map[string]interface{}{
				"location": map[string]interface{}{
					"type":        []interface{}{"string"},
					"description": "The location to get weather for",
				},
				"unit": map[string]interface{}{
					"type":        []interface{}{"string", "null"},
					"description": "The unit of temperature (celsius or fahrenheit)",
					"enum":        []interface{}{"celsius", "fahrenheit"},
				},
			},
			"required":             []interface{}{"location"},
			"additionalProperties": false,
		},
	}

	// This should not panic and should successfully normalize the schema
	ollamaTools := provider.convertTools([]types.Tool{tool})
	require.Len(t, ollamaTools, 1)

	// Verify the result can be successfully marshaled
	jsonData, err := json.Marshal(ollamaTools[0])
	require.NoError(t, err)

	// Verify the JSON structure is correct
	var result map[string]interface{}
	err = json.Unmarshal(jsonData, &result)
	require.NoError(t, err)

	// Verify the normalized types
	function := result["function"].(map[string]interface{})
	params := function["parameters"].(map[string]interface{})
	properties := params["properties"].(map[string]interface{})

	location := properties["location"].(map[string]interface{})
	assert.Equal(t, "string", location["type"])

	unit := properties["unit"].(map[string]interface{})
	assert.Equal(t, "string", unit["type"])

	// Verify other properties are preserved
	assert.Equal(t, "The unit of temperature (celsius or fahrenheit)", unit["description"])
	assert.NotNil(t, unit["enum"])
}
